### ISSUE TITLE
Good version of Sea Ice drift

### ISSUE THREAD

**Issue by lucearth** [nansencenter/sea_ice_drift#11]
Hi, 
I have some troubles to find the good archive for sea ice drift. I tried to download version 0.6 with pip install but there is no recent changes incorporated in this version (still argument referring to old Nansat for instance), 
Is there a good link for getting the latest version ?
Also, I have the feeling that recent changes are made for python 3 (recent printing commit in PMlib), I am running on python 2.7, do you recommend to upgrade to python 3 ?
In the end, I struggle to install Sea ice drift with the last version of nansat because of all dependancies.

Thanks a lot,
Luc

**Comment by akorosov** [comment]
Fixed in fcc83a0b744729ddf9caa0ba7f3cfdbc729dccb5

Hi @lucearth ,
I've updated sea ice drift, made sure it is compatible with the recent Nansat and released v0.7. Both py27 and py36 should work. Note that installation instructions changed slightly. I find using conda environments to be very practical.

Best regards!
Anton
